platform :ios, '8.4'

target 'CAPhotoCacheDemo' do
  use_frameworks!

  # Pods for CAPhotoCacheDemo
  pod 'CAPhotoCache', :path => '../'
  pod 'SSZipArchive'
  pod 'AFNetworking'

  target 'CAPhotoCacheDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
